### ISSUE TITLE
Redesign navbar

### ISSUE THREAD

**Issue by GiangNPham** [ripe-money/monitor#5]
Create a more suitable navbar 
Need Ripe's logo

**Comment by chucklam** [comment]
![WhiteLogo](https://github.com/ripe-money/monitor/assets/939400/d62c11a5-0a2e-4c93-9ba3-4b9793f06481)
![icon-512x512](https://github.com/ripe-money/monitor/assets/939400/c5c2f36f-2187-491a-9e0b-7b80690dd250)
![icon-192x192](https://github.com/ripe-money/monitor/assets/939400/6c4ee4d5-08c5-474f-a5a0-228d62fc90f2)
![icon-180x180](https://github.com/ripe-money/monitor/assets/939400/13f6c75c-53c0-4613-b7fe-342def06fb05)
![icon](https://github.com/ripe-money/monitor/assets/939400/5d68e12c-851d-479c-a024-fa342434e85a)

First one is the brand logo in white. The rest are for favicon and other icons.

(@me in your message would've made it more explicit that I needed to respond.)
